TEMPLATE = app
CONFIG += console c++17
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
        Behavioral/Chain_of_responsibility/Chain_of_responsibility1/chain_of_responsibility.cpp \
        Behavioral/Chain_of_responsibility/Chain_of_responsibility1/test_chain_of_responsibility1.cpp \
        Behavioral/Command/Command1/command1.cpp \
        Behavioral/Command/Command1/test_command1.cpp \
        Behavioral/Command/Command1/usecase_command1.cpp \
        Behavioral/Interpreter/Interpreter1/interpreter1.cpp \
        Behavioral/Interpreter/Interpreter1/test_interpreter1.cpp \
        Behavioral/Iterator/Iterator1/iterator1.cpp \
        Behavioral/Iterator/Iterator1/test_iterator1.cpp \
        Behavioral/Iterator/Iterator1/usecase_iterator1.cpp \
        Behavioral/Mediator/Mediator1/mediator1.cpp \
        Behavioral/Mediator/Mediator1/test_mediator1.cpp \
        Behavioral/Mediator/Mediator1/usecase_mediator1.cpp \
        Behavioral/Memento/Memento1/memento1.cpp \
        Behavioral/Memento/Memento1/test_memento1.cpp \
        Behavioral/Observer/Observer1/observer1.cpp \
        Behavioral/Observer/Observer1/test_observer1.cpp \
        Behavioral/Observer/Observer1/usecase_observer1.cpp \
        Behavioral/State/State1/state1.cpp \
        Behavioral/State/State1/test_state1.cpp \
        Behavioral/Strategy/Strategy1/strategy1.cpp \
        Behavioral/Strategy/Strategy1/test_strategy1.cpp \
        Behavioral/Strategy/Strategy1/usecase_strategy1.cpp \
        Behavioral/Template_method/Template_method1/template_method1.cpp \
        Behavioral/Template_method/Template_method1/test_template_method1.cpp \
        Behavioral/Template_method/Template_method1/usecase_template_method1.cpp \
        Creational/ObjectPool/ObjectPool1/object_pool1.cpp \
        Creational/ObjectPool/ObjectPool1/test_object_pool1.cpp \
        Creational/ObjectPool/ObjectPool1/usecase_object_pool1.cpp \
        Creational/Singleton1/singleton.cpp \
        Creational/Singleton1/test_singleton.cpp \
        Creational/abstract_factory/abstract_factory.cpp \
        Creational/abstract_factory/test_abstract_factory.cpp \
        Creational/abstract_factory/usecase_abstract_factory.cpp \
        Creational/builder/builder1/builder1.cpp \
        Creational/builder/builder1/test_builder1.cpp \
        Creational/builder/builder1/usecase_builder1.cpp \
        Creational/factory1/factory.cpp \
        Creational/factory1/test_factory.cpp \
        Creational/factory1/usecase_factory.cpp \
        Creational/prototype/prototype1/prototype1.cpp \
        Creational/prototype/prototype1/test_prototype1.cpp \
        Creational/prototype/prototype1/usecase_prototype1.cpp \
        Structural/Adapter/Adapter1/adapter.cpp \
        Structural/Adapter/Adapter1/test_adapter1.cpp \
        Structural/Adapter/Adapter1/usecase_adapter1.cpp \
        Structural/Bridge/Bridge1/bridge1.cpp \
        Structural/Bridge/Bridge1/test_bridge1.cpp \
        Structural/Bridge/Bridge1/usecase_bridge1.cpp \
        Structural/Composite/Composite1/composite1.cpp \
        Structural/Composite/Composite1/test_composite1.cpp \
        Structural/Composite/Composite1/usecase_composite1.cpp \
        Structural/Decorator/Decorator1/decorator1.cpp \
        Structural/Decorator/Decorator1/test_decorator1.cpp \
        Structural/Decorator/Decorator1/usecase_decorator1.cpp \
        Structural/Facade/Facade1/facade1.cpp \
        Structural/Facade/Facade1/test_facade1.cpp \
        Structural/Facade/Facade1/usecase_facade1.cpp \
        Structural/Flyweight/Flyweight1/flyweight1.cpp \
        Structural/Flyweight/Flyweight1/test_flyweight1.cpp \
        Structural/Flyweight/Flyweight1/usecase_flyweight1.cpp \
        Structural/Proxy/Proxy1/proxy1.cpp \
        Structural/Proxy/Proxy1/test_proxy1.cpp \
        Structural/Proxy/Proxy1/usecase_proxy1.cpp \
        Structural/Proxy/Proxy2/smart_pointer.cpp \
        Structural/Proxy/Proxy2/templates_proxy2.cpp \
        Structural/Proxy/Proxy2/test_proxy2.cpp \
        Structural/Proxy/Proxy2/usecase_proxy2.cpp \
        main.cpp

HEADERS += \
    Behavioral/Chain_of_responsibility/Chain_of_responsibility1/chain_of_responsibility.h \
    Behavioral/Chain_of_responsibility/Chain_of_responsibility1/test_chain_of_responsibility1.h \
    Behavioral/Command/Command1/command1.h \
    Behavioral/Command/Command1/test_command1.h \
    Behavioral/Command/Command1/usecase_command1.h \
    Behavioral/Interpreter/Interpreter1/interpreter1.h \
    Behavioral/Interpreter/Interpreter1/test_interpreter1.h \
    Behavioral/Iterator/Iterator1/iterator1.h \
    Behavioral/Iterator/Iterator1/test_iterator1.h \
    Behavioral/Iterator/Iterator1/usecase_iterator1.h \
    Behavioral/Mediator/Mediator1/mediator1.h \
    Behavioral/Mediator/Mediator1/test_mediator1.h \
    Behavioral/Mediator/Mediator1/usecase_mediator1.h \
    Behavioral/Memento/Memento1/memento1.h \
    Behavioral/Memento/Memento1/test_memento1.h \
    Behavioral/Observer/Observer1/observer1.h \
    Behavioral/Observer/Observer1/test_observer1.h \
    Behavioral/Observer/Observer1/usecase_observer1.h \
    Behavioral/State/State1/state1.h \
    Behavioral/State/State1/test_state1.h \
    Behavioral/Strategy/Strategy1/strategy1.h \
    Behavioral/Strategy/Strategy1/test_strategy1.h \
    Behavioral/Strategy/Strategy1/usecase_strategy1.h \
    Behavioral/Template_method/Template_method1/template_method1.h \
    Behavioral/Template_method/Template_method1/test_template_method1.h \
    Behavioral/Template_method/Template_method1/usecase_template_method1.h \
    Creational/ObjectPool/ObjectPool1/object_pool1.h \
    Creational/ObjectPool/ObjectPool1/test_object_pool1.h \
    Creational/ObjectPool/ObjectPool1/usecase_object_pool1.h \
    Creational/Singleton1/singleton.h \
    Creational/Singleton1/test_singleton.h \
    Creational/abstract_factory/abstract_factory.h \
    Creational/abstract_factory/test_abstract_factory.h \
    Creational/abstract_factory/usecase_abstract_factory.h \
    Creational/builder/builder1/builder1.h \
    Creational/builder/builder1/test_builder1.h \
    Creational/builder/builder1/usecase_builder1.h \
    Creational/factory1/factory.h \
    Creational/factory1/test_factory.h \
    Creational/factory1/usecase_factory.h \
    Creational/prototype/prototype1/prototype1.h \
    Creational/prototype/prototype1/test_prototype1.h \
    Creational/prototype/prototype1/usecase_prototype1.h \
    Structural/Adapter/Adapter1/adapter.h \
    Structural/Adapter/Adapter1/test_adapter1.h \
    Structural/Adapter/Adapter1/usecase_adapter1.h \
    Structural/Bridge/Bridge1/bridge1.h \
    Structural/Bridge/Bridge1/test_bridge1.h \
    Structural/Bridge/Bridge1/usecase_bridge1.h \
    Structural/Composite/Composite1/composite1.h \
    Structural/Composite/Composite1/test_composite1.h \
    Structural/Composite/Composite1/usecase_composite1.h \
    Structural/Decorator/Decorator1/decorator1.h \
    Structural/Decorator/Decorator1/test_decorator1.h \
    Structural/Decorator/Decorator1/usecase_decorator1.h \
    Structural/Facade/Facade1/facade1.h \
    Structural/Facade/Facade1/test_facade1.h \
    Structural/Facade/Facade1/usecase_facade1.h \
    Structural/Flyweight/Flyweight1/flyweight1.h \
    Structural/Flyweight/Flyweight1/test_flyweight1.h \
    Structural/Flyweight/Flyweight1/usecase_flyweight1.h \
    Structural/Proxy/Proxy1/proxy1.h \
    Structural/Proxy/Proxy1/test_proxy1.h \
    Structural/Proxy/Proxy1/usecase_proxy1.h \
    Structural/Proxy/Proxy2/smart_pointer.h \
    Structural/Proxy/Proxy2/test_proxy2.h \
    Structural/Proxy/Proxy2/usecase_proxy2.h
